/**
 * Excel Examples
 *
 * Demonstrates Excel workbook creation using ketrics.Excel.
 * Generated workbooks can be saved to a volume for download.
 */

/**
 * Create a spreadsheet with headers and sample data.
 */
const createSpreadsheet = async () => {
  const workbook = ketrics.Excel.create();

  // Create a worksheet with column definitions
  const sheet = workbook.addWorksheet("Employees", {
    tabColor: "4472C4",
  });

  // Define columns
  sheet.columns = [
    { header: "ID", key: "id", width: 10 },
    { header: "Name", key: "name", width: 25 },
    { header: "Department", key: "department", width: 20 },
    { header: "Start Date", key: "startDate", width: 15 },
    { header: "Salary", key: "salary", width: 15 },
  ];

  // Add rows
  const employees = [
    { id: 1, name: "Alice Johnson", department: "Engineering", startDate: "2024-01-15", salary: 95000 },
    { id: 2, name: "Bob Smith", department: "Marketing", startDate: "2023-06-01", salary: 78000 },
    { id: 3, name: "Carol Williams", department: "Engineering", startDate: "2024-03-20", salary: 105000 },
    { id: 4, name: "David Brown", department: "Sales", startDate: "2023-09-10", salary: 82000 },
    { id: 5, name: "Eva Martinez", department: "Engineering", startDate: "2024-07-01", salary: 92000 },
  ];

  sheet.addRows(employees);

  // Save to volume
  const buffer = await workbook.toBuffer();
  const volume = await ketrics.Volume.connect("test-volume");
  const result = await volume.put("reports/employees.xlsx", buffer, {
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const downloadUrl = await volume.generateDownloadUrl("reports/employees.xlsx", {
    expiresIn: 3600,
  });

  return {
    file: { key: result.key, size: result.size },
    downloadUrl: downloadUrl.url,
    rowCount: employees.length,
  };
};

/**
 * Export dynamic data to Excel - demonstrates creating a multi-sheet
 * workbook with a summary sheet and a data sheet.
 */
const exportDataToExcel = async (payload: { title?: string }) => {
  const title = payload?.title || "Data Export";

  const workbook = ketrics.Excel.create();

  // Summary sheet
  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.columns = [
    { header: "Property", key: "property", width: 25 },
    { header: "Value", key: "value", width: 40 },
  ];

  summarySheet.addRows([
    { property: "Report Title", value: title },
    { property: "Generated By", value: ketrics.application.name },
    { property: "Tenant", value: ketrics.tenant.name },
    { property: "Generated At", value: new Date().toISOString() },
    { property: "Requestor", value: ketrics.requestor.name },
  ]);

  // Data sheet with sample data
  const dataSheet = workbook.addWorksheet("Data");
  dataSheet.columns = [
    { header: "Category", key: "category", width: 20 },
    { header: "Month", key: "month", width: 15 },
    { header: "Revenue", key: "revenue", width: 15 },
    { header: "Expenses", key: "expenses", width: 15 },
    { header: "Profit", key: "profit", width: 15 },
  ];

  const sampleData = [
    { category: "Product A", month: "January", revenue: 50000, expenses: 30000, profit: 20000 },
    { category: "Product A", month: "February", revenue: 55000, expenses: 31000, profit: 24000 },
    { category: "Product B", month: "January", revenue: 35000, expenses: 20000, profit: 15000 },
    { category: "Product B", month: "February", revenue: 40000, expenses: 22000, profit: 18000 },
  ];

  dataSheet.addRows(sampleData);

  // Save to volume
  const buffer = await workbook.toBuffer();
  const volume = await ketrics.Volume.connect("test-volume");
  const fileName = `reports/export-${Date.now()}.xlsx`;
  const result = await volume.put(fileName, buffer, {
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const downloadUrl = await volume.generateDownloadUrl(fileName, { expiresIn: 3600 });

  return {
    file: { key: result.key, size: result.size },
    downloadUrl: downloadUrl.url,
    sheets: ["Summary", "Data"],
    dataRowCount: sampleData.length,
  };
};

export { createSpreadsheet, exportDataToExcel };
