/**
 * Excel Examples
 *
 * Demonstrates Excel workbook creation using ketrics.Excel.
 * Generated workbooks can be saved to a volume for download.
 */

import { attachmentDisposition, demoVolumeCode } from "./helpers";
import { requirePermission } from "./permissions";

/**
 * Create a spreadsheet with headers and sample data.
 */
const createSpreadsheet = async () => {
  requirePermission("export");

  const workbook = ketrics.Excel.create();

  // Create a worksheet with column definitions
  const sheet = workbook.addWorksheet("Employees", {
    tabColor: "4472C4",
  });

  // Define columns
  sheet.columns = [
    { header: "ID", key: "id", width: 10 },
    { header: "Name", key: "name", width: 25 },
    { header: "Department", key: "department", width: 20 },
    { header: "Start Date", key: "startDate", width: 15 },
    { header: "Salary", key: "salary", width: 15 },
  ];

  // Add rows. addRows takes arrays of cell values, positional to the columns
  // defined above - not objects keyed by column key.
  const employees = [
    [1, "Alice Johnson", "Engineering", "2024-01-15", 95000],
    [2, "Bob Smith", "Marketing", "2023-06-01", 78000],
    [3, "Carol Williams", "Engineering", "2024-03-20", 105000],
    [4, "David Brown", "Sales", "2023-09-10", 82000],
    [5, "Eva Martinez", "Engineering", "2024-07-01", 92000],
  ];

  sheet.addRows(employees);

  // Save to volume
  const buffer = await workbook.toBuffer();
  const volume = await ketrics.Volume.connect(demoVolumeCode());
  const result = await volume.put("reports/employees.xlsx", buffer, {
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  // responseContentDisposition is required — see attachmentDisposition in ./helpers
  const downloadUrl = await volume.generateDownloadUrl("reports/employees.xlsx", {
    expiresIn: 3600,
    responseContentDisposition: attachmentDisposition("employees.xlsx"),
  });

  return {
    file: { key: result.key, size: result.size },
    downloadUrl: downloadUrl.url,
    rowCount: employees.length,
  };
};

/**
 * Export dynamic data to Excel - demonstrates creating a multi-sheet
 * workbook with a summary sheet and a data sheet.
 */
const exportDataToExcel = async (payload: { title?: string }) => {
  requirePermission("export");

  const title = payload?.title || "Data Export";

  const workbook = ketrics.Excel.create();

  // Summary sheet
  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.columns = [
    { header: "Property", key: "property", width: 25 },
    { header: "Value", key: "value", width: 40 },
  ];

  summarySheet.addRows([
    ["Report Title", title],
    ["Generated By", ketrics.application.name],
    ["Tenant", ketrics.tenant.name],
    ["Generated At", new Date().toISOString()],
    ["Requestor", ketrics.requestor.name],
  ]);

  // Data sheet with sample data
  const dataSheet = workbook.addWorksheet("Data");
  dataSheet.columns = [
    { header: "Category", key: "category", width: 20 },
    { header: "Month", key: "month", width: 15 },
    { header: "Revenue", key: "revenue", width: 15 },
    { header: "Expenses", key: "expenses", width: 15 },
    { header: "Profit", key: "profit", width: 15 },
  ];

  const sampleData = [
    ["Product A", "January", 50000, 30000, 20000],
    ["Product A", "February", 55000, 31000, 24000],
    ["Product B", "January", 35000, 20000, 15000],
    ["Product B", "February", 40000, 22000, 18000],
  ];

  dataSheet.addRows(sampleData);

  // Save to volume
  const buffer = await workbook.toBuffer();
  const volume = await ketrics.Volume.connect(demoVolumeCode());
  const downloadName = `export-${Date.now()}.xlsx`;
  const fileName = `reports/${downloadName}`;
  const result = await volume.put(fileName, buffer, {
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const downloadUrl = await volume.generateDownloadUrl(fileName, {
    expiresIn: 3600,
    responseContentDisposition: attachmentDisposition(downloadName),
  });

  return {
    file: { key: result.key, size: result.size },
    downloadUrl: downloadUrl.url,
    sheets: ["Summary", "Data"],
    dataRowCount: sampleData.length,
  };
};

export { createSpreadsheet, exportDataToExcel };
