/**
 * PDF Examples
 *
 * Demonstrates PDF document creation using ketrics.Pdf.
 * Generated PDFs can be saved to a volume for download.
 */

/**
 * Create a simple PDF document and save it to a volume.
 */
const createSimplePdf = async () => {
  const doc = await ketrics.Pdf.create();

  // Set document metadata
  doc.setTitle("Sample Document");
  doc.setAuthor(ketrics.tenant.name);
  doc.setCreator(ketrics.application.name);

  // Add a page
  const page = doc.addPage({ size: "A4" });

  // Embed a standard font
  const font = await doc.embedStandardFont("Helvetica");
  const boldFont = await doc.embedStandardFont("Helvetica-Bold");

  // Draw title
  page.drawText("Hello from Ketrics!", {
    x: 50,
    y: 780,
    size: 28,
    font: boldFont,
    color: ketrics.Pdf.rgb(0.2, 0.2, 0.6),
  });

  // Draw subtitle
  page.drawText(`Generated by ${ketrics.application.name} for ${ketrics.tenant.name}`, {
    x: 50,
    y: 750,
    size: 12,
    font,
    color: ketrics.Pdf.rgb(0.4, 0.4, 0.4),
  });

  // Draw a decorative line
  page.drawLine({
    start: { x: 50, y: 740 },
    end: { x: 545, y: 740 },
    thickness: 2,
    color: ketrics.Pdf.rgb(0.2, 0.2, 0.6),
  });

  // Draw body text
  page.drawText("This PDF was generated dynamically using the Ketrics PDF SDK.", {
    x: 50,
    y: 710,
    size: 14,
    font,
    color: ketrics.Pdf.rgb(0, 0, 0),
  });

  page.drawText(`Date: ${new Date().toISOString()}`, {
    x: 50,
    y: 685,
    size: 11,
    font,
    color: ketrics.Pdf.rgb(0.3, 0.3, 0.3),
  });

  // Save to volume
  const buffer = await doc.toBuffer();
  const volume = await ketrics.Volume.connect("test-volume");
  const result = await volume.put("documents/sample.pdf", buffer, {
    contentType: "application/pdf",
  });

  // Generate download URL
  const downloadUrl = await volume.generateDownloadUrl("documents/sample.pdf", {
    expiresIn: 3600,
  });

  return {
    file: { key: result.key, size: result.size },
    downloadUrl: downloadUrl.url,
    pageCount: doc.getPageCount(),
  };
};

/**
 * Create an invoice-style PDF with structured data.
 */
const createInvoicePdf = async (payload: {
  invoiceNumber?: string;
  customerName?: string;
  items?: Array<{ description: string; quantity: number; price: number }>;
}) => {
  const invoiceNumber = payload?.invoiceNumber || "INV-001";
  const customerName = payload?.customerName || "Sample Customer";
  const items = payload?.items || [
    { description: "Web Development", quantity: 40, price: 150 },
    { description: "Design Services", quantity: 20, price: 120 },
    { description: "Consulting", quantity: 10, price: 200 },
  ];

  const doc = await ketrics.Pdf.create();
  doc.setTitle(`Invoice ${invoiceNumber}`);
  doc.setAuthor(ketrics.tenant.name);

  const page = doc.addPage({ size: "A4" });
  const font = await doc.embedStandardFont("Helvetica");
  const boldFont = await doc.embedStandardFont("Helvetica-Bold");

  let y = 780;

  // Header
  page.drawText("INVOICE", {
    x: 50, y, size: 32, font: boldFont,
    color: ketrics.Pdf.rgb(0.2, 0.2, 0.6),
  });

  y -= 35;
  page.drawText(`#${invoiceNumber}`, {
    x: 50, y, size: 14, font,
    color: ketrics.Pdf.rgb(0.4, 0.4, 0.4),
  });

  // Company info (right side)
  page.drawText(ketrics.tenant.name, {
    x: 400, y: 780, size: 14, font: boldFont,
    color: ketrics.Pdf.rgb(0, 0, 0),
  });

  page.drawText(new Date().toLocaleDateString(), {
    x: 400, y: 762, size: 11, font,
    color: ketrics.Pdf.rgb(0.4, 0.4, 0.4),
  });

  // Divider
  y -= 20;
  page.drawLine({
    start: { x: 50, y },
    end: { x: 545, y },
    thickness: 1,
    color: ketrics.Pdf.rgb(0.8, 0.8, 0.8),
  });

  // Bill To
  y -= 30;
  page.drawText("Bill To:", { x: 50, y, size: 10, font, color: ketrics.Pdf.rgb(0.5, 0.5, 0.5) });
  y -= 18;
  page.drawText(customerName, { x: 50, y, size: 14, font: boldFont, color: ketrics.Pdf.rgb(0, 0, 0) });

  // Table header
  y -= 40;
  page.drawRectangle({
    x: 50, y: y - 5, width: 495, height: 25,
    color: ketrics.Pdf.rgb(0.93, 0.93, 0.97),
  });

  page.drawText("Description", { x: 60, y, size: 10, font: boldFont, color: ketrics.Pdf.rgb(0.3, 0.3, 0.3) });
  page.drawText("Qty", { x: 330, y, size: 10, font: boldFont, color: ketrics.Pdf.rgb(0.3, 0.3, 0.3) });
  page.drawText("Price", { x: 400, y, size: 10, font: boldFont, color: ketrics.Pdf.rgb(0.3, 0.3, 0.3) });
  page.drawText("Total", { x: 480, y, size: 10, font: boldFont, color: ketrics.Pdf.rgb(0.3, 0.3, 0.3) });

  // Table rows
  let grandTotal = 0;
  for (const item of items) {
    y -= 25;
    const lineTotal = item.quantity * item.price;
    grandTotal += lineTotal;

    page.drawText(item.description, { x: 60, y, size: 11, font, color: ketrics.Pdf.rgb(0, 0, 0) });
    page.drawText(String(item.quantity), { x: 335, y, size: 11, font, color: ketrics.Pdf.rgb(0, 0, 0) });
    page.drawText(`$${item.price.toFixed(2)}`, { x: 395, y, size: 11, font, color: ketrics.Pdf.rgb(0, 0, 0) });
    page.drawText(`$${lineTotal.toFixed(2)}`, { x: 475, y, size: 11, font, color: ketrics.Pdf.rgb(0, 0, 0) });
  }

  // Total
  y -= 15;
  page.drawLine({
    start: { x: 380, y },
    end: { x: 545, y },
    thickness: 1,
    color: ketrics.Pdf.rgb(0.8, 0.8, 0.8),
  });

  y -= 20;
  page.drawText("Total:", { x: 400, y, size: 14, font: boldFont, color: ketrics.Pdf.rgb(0, 0, 0) });
  page.drawText(`$${grandTotal.toFixed(2)}`, {
    x: 470, y, size: 14, font: boldFont,
    color: ketrics.Pdf.rgb(0.2, 0.2, 0.6),
  });

  // Save to volume
  const buffer = await doc.toBuffer();
  const volume = await ketrics.Volume.connect("test-volume");
  const fileName = `invoices/${invoiceNumber}.pdf`;
  const result = await volume.put(fileName, buffer, {
    contentType: "application/pdf",
  });

  const downloadUrl = await volume.generateDownloadUrl(fileName, { expiresIn: 3600 });

  return {
    file: { key: result.key, size: result.size },
    downloadUrl: downloadUrl.url,
    invoiceNumber,
    total: grandTotal,
    itemCount: items.length,
  };
};

export { createSimplePdf, createInvoicePdf };
