/**
 * Mock Backend Handlers
 *
 * Define mock responses for your backend functions here.
 * These are used automatically when running `npm run dev` (local development)
 * and are completely excluded from production builds.
 *
 * Each key corresponds to a backend function name exported from backend/src/index.ts.
 * The handler receives the same payload your backend function would receive
 * and should return the same response shape.
 *
 * Usage:
 *   1. Add a handler for each backend function you want to mock
 *   2. Run `npm run dev` - the frontend will use these handlers instead of the runtime API
 *   3. Run `npm run build` / `ketrics deploy` - mock code is stripped out entirely
 */

type MockHandler = (payload?: unknown) => unknown | Promise<unknown>;

const handlers: Record<string, MockHandler> = {
  echo: (payload) => ({
    payload,
    context: {
      tenant: { id: "mock-tenant-id", code: "mock-tenant", name: "Mock Tenant" },
      application: { id: "mock-app-id", code: "mock-app", name: "Mock App", version: "1.0.0", deploymentId: "mock-deploy" },
      requestor: { type: "user", userId: "mock-user-id", email: "dev@localhost", name: "Local Developer", applicationPermissions: [] },
      runtime: { nodeVersion: "18.x", runtime: "mock", region: "local" },
      environment: {},
    },
  }),

  info: () => ({
    tenant: { id: "mock-tenant-id", code: "mock-tenant", name: "Mock Tenant" },
    application: { id: "mock-app-id", code: "mock-app", name: "Mock App", version: "1.0.0" },
    runtime: { nodeVersion: "18.x", runtime: "mock", region: "local" },
  }),

  fetchExternalApi: () => ({
    data: { id: 1, title: "Mock Post", body: "This is a mock response from the local dev server." },
    fetchedAt: new Date().toISOString(),
  }),

  // --- Volumes ---

  saveFile: () => ({
    jsonFile: { key: "output/data.json", etag: "mock-etag-1", size: 128 },
    textFile: { key: "output/hello.txt", etag: "mock-etag-2", size: 19 },
  }),

  readFile: () => ({
    contentType: "application/json",
    contentLength: 128,
    lastModified: new Date().toISOString(),
    parsed: { generatedBy: "mock-app", generatedAt: new Date().toISOString(), tenant: "mock-tenant" },
  }),

  listFiles: (payload: unknown) => {
    const { prefix } = (payload as { prefix?: string }) || {};
    return {
      files: [
        { key: `${prefix || "output/"}data.json`, size: 128, lastModified: new Date().toISOString(), contentType: "application/json" },
        { key: `${prefix || "output/"}hello.txt`, size: 19, lastModified: new Date().toISOString(), contentType: "text/plain" },
      ],
      count: 2,
      isTruncated: false,
    };
  },

  generateDownloadUrl: () => ({
    url: "https://example.com/mock-download-url",
    expiresAt: new Date(Date.now() + 3600_000).toISOString(),
  }),

  copyFile: () => ({
    sourceKey: "output/data.json",
    destinationKey: "backup/data-backup.json",
    etag: "mock-etag-copy",
  }),

  // --- Database ---

  queryUsers: (payload: unknown) => {
    const { limit } = (payload as { limit?: number }) || {};
    const users = [
      { id: 1, name: "Alice Johnson", email: "alice@example.com" },
      { id: 2, name: "Bob Smith", email: "bob@example.com" },
      { id: 3, name: "Carol Davis", email: "carol@example.com" },
      { id: 4, name: "Dan Wilson", email: "dan@example.com" },
      { id: 5, name: "Eve Martinez", email: "eve@example.com" },
    ];
    const sliced = users.slice(0, limit || 10);
    return { users: sliced, rowCount: sliced.length };
  },

  insertRecord: (payload: unknown) => {
    const { name, email } = (payload as { name?: string; email?: string }) || {};
    if (!name || !email) throw new Error("name and email are required");
    return { affectedRows: 1, insertId: Math.floor(Math.random() * 1000) + 100 };
  },

  transferFunds: (payload: unknown) => {
    const { amount } = (payload as { amount?: number }) || {};
    if (!amount || amount <= 0) throw new Error("Amount must be positive");
    return { transferred: amount };
  },

  // --- Documents ---

  createSimplePdf: () => ({
    downloadUrl: "https://example.com/mock-simple.pdf",
    message: "[Mock] PDF would be generated by the backend",
  }),

  createInvoicePdf: () => ({
    downloadUrl: "https://example.com/mock-invoice.pdf",
    message: "[Mock] Invoice PDF would be generated by the backend",
  }),

  createSpreadsheet: () => ({
    downloadUrl: "https://example.com/mock-spreadsheet.xlsx",
    message: "[Mock] Spreadsheet would be generated by the backend",
  }),

  exportDataToExcel: () => ({
    downloadUrl: "https://example.com/mock-export.xlsx",
    message: "[Mock] Excel export would be generated by the backend",
  }),

  // --- Messaging & Jobs ---

  sendNotification: (payload: unknown) => {
    const { subject, body } = (payload as { subject?: string; body?: string }) || {};
    return { sent: true, subject, body, message: "[Mock] Notification would be sent by the backend" };
  },

  scheduleBackgroundJob: () => ({
    jobId: `mock-job-${Date.now()}`,
    status: "scheduled",
    message: "[Mock] Job would be scheduled by the backend",
  }),

  getSecret: () => ({
    value: "mock-secret-value",
    message: "[Mock] Secret would be retrieved from the backend",
  }),
};

export { handlers };
export type { MockHandler };
